WINDOW_SIZE = 800
GRAPHICS_ON = True
BACKGROUND_COLOUR_GL = (0, 0, 0, 1)
DEVICE_DEFAULT_COLOUR = (50, 225, 30)
RANDOM_SEED = 114510
UPDATE_RATE = 5
KMEANS_RATE = 1
PORT = 1883

NUMBER_OF_DEVICES = 10
COMM_RANGE = 30
MOVE_SPEED = 0.2

DKMEANS_ITERATIONS = 5
MIN_CLUSTER_SIZE = 3

## Training parameters
BATCH_SIZE = 2
NUMBER_OF_CLASSES_PER_CLIENT = 1
DATA_PATH = "dataset"
DEVICE = "gpu"
NUM_OF_CLASSES = 10
NUM_EPOCHS = 5
