WINDOW_SIZE = 800
GRAPHICS_ON = True
BACKGROUND_COLOUR_GL = (0, 0, 0, 1)
DEVICE_DEFAULT_COLOUR = (50, 225, 30)
RANDOM_SEED = 114510
UPDATE_RATE = 5
KMEANS_RATE = 1
PORT = 1883

NUMBER_OF_DEVICES = 50
COMM_RANGE = 20
MOVE_SPEED = 0.8

DKMEANS_ITERATIONS = 5
MIN_CLUSTER_SIZE = 3
INNER_GOSSIP_ITERATIONS = 4
INTER_GOSSIP_ITERATIONS = 4

## Training parameters
BATCH_SIZE = 128
NUM_EPOCHS = 4
# NUMBER_OF_CLASSES_PER_CLIENT = 7
NON_IID_ALPHA = 0.5
DATA_PATH = "dataset"
DEVICE = "cuda"
NUM_OF_CLASSES = 10


